# Initialisation / demarrage
CODE_MAIN_DEMARRAGE = const((1,1))
CODE_CONFIG_INITIALISATION = const((1,2))
CODE_MAIN_OPERATION_INCONNUE = const((1,3))

CODE_WIFI_NON_CONNECTE = const((3,1))

# Erreurs
CODE_POLLING_ERREUR_GENERALE = const((4,1))
CODE_ERREUR_MEMOIRE = const((4,2))
CODE_MAIN_ERREUR_GENERALE = const((4,3))
